#!/usr/bin/env python3
"""
Daily FDE Learning Coach Bot
----------------------------
A 15-20 minute daily learning session for a senior manager/FDE-lead
maintaining hands-on AI/ML + engineering depth. Each day has a deep-dive
pillar based on day of week (Mon=AI/ML, Tue=SWE, Wed=news roundup,
Thu=FDE case study, Fri=Martech, Sat=eng leadership, Sun=weekly recap/quiz),
wrapped in the same lightweight daily template every day. Generated by
Claude with web search, then sent by email (Resend API) and Telegram
(Telegram Bot API).

Designed to run on a schedule (cron / GitHub Actions) alongside your
existing WhatsApp goal-notifier script.

SETUP
-----
1. pip install anthropic python-dotenv
2. Email (Resend): create a free account at https://resend.com and copy
   an API key from the dashboard (starts with "re_").
3. Telegram: message @BotFather on Telegram, send "/newbot", follow the
   prompts, and copy the bot token it gives you. Then send your new bot
   any message (e.g. "hi") so it can see your chat, and visit
   https://api.telegram.org/bot<YOUR_TOKEN>/getUpdates in a browser to
   find your numeric chat id under "message" -> "chat" -> "id".
4. Create a .env file (same folder) with:
       ANTHROPIC_API_KEY=sk-ant-...
       RESEND_API_KEY=re_...
       EMAIL_TO=you@example.com
       EMAIL_FROM=onboarding@resend.dev              # optional; see note below
       TELEGRAM_BOT_TOKEN=123456789:AA...
       TELEGRAM_CHAT_ID=123456789
   Note: the shared "onboarding@resend.dev" sender only delivers to the
   email address you signed up to Resend with. To send to any address,
   verify your own domain in the Resend dashboard and set EMAIL_FROM to
   an address on it (e.g. bot@yourdomain.com).
5. Test: python daily_ai_nugget.py --dry-run   (prints message, doesn't send)
6. Schedule it (see .github/workflows/daily-nugget.yml for the GitHub
   Actions version, which runs daily at 9:30 AM IST).

CUSTOMIZING TOPICS
------------------
Edit TOPIC_BANKS to change what each pillar covers. Each pillar has its
own rotating cursor persisted in coach_state.json, so subtopics cycle
through without repeating. PILLAR_BY_WEEKDAY controls which pillar is the
deep-dive for which day (index 0 = Monday ... 6 = Sunday, matching
datetime.weekday()).

NOTE ON INTERACTIVITY
----------------------
The source instructions this bot follows (a conversational "coach" prompt)
assume a live chat where you can reply "quiz me", "more depth", etc., and
where the coach waits to see if you attempted yesterday's interview
question before revealing the answer. This bot is a one-way scheduled
send with no reply-parsing, so those interactive bits are adapted:
the model answer to each day's interview question is always revealed at
the start of the *next* day's message (regardless of whether you actually
attempted it), and steering commands aren't wired up.
"""

import os
import re
import sys
import json
import argparse
from datetime import datetime, date, timezone, timedelta
from pathlib import Path

from dotenv import load_dotenv
import anthropic

if sys.stdout.encoding != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")

load_dotenv()

SCRIPT_DIR = Path(__file__).parent
STATE_FILE = SCRIPT_DIR / "coach_state.json"

IST = timezone(timedelta(hours=5, minutes=30))


def now_ist() -> datetime:
    return datetime.now(IST)


# While today is before this date, every section is written at a 101/foundations
# level (define building-block terms before any comparison/tradeoff, prioritize
# beginner-level video links). After this date, it reverts to the senior/staff-level
# calibration. Extend this (or set it further out) if more ramp-up time is needed;
# set it to today or the past to switch back to advanced immediately.
FOUNDATIONS_MODE_UNTIL = date(2026, 12, 25)


# Day-of-week (datetime.weekday(): Monday=0 ... Sunday=6) -> deep-dive pillar.
PILLAR_BY_WEEKDAY = [
    "ai_ml",         # Monday
    "swe",           # Tuesday
    "news_roundup",  # Wednesday
    "fde_case",      # Thursday
    "martech",       # Friday
    "leadership",    # Saturday
    "review_quiz",   # Sunday
]

PILLAR_LABELS = {
    "ai_ml": "AI/ML core concepts",
    "swe": "Software & systems engineering",
    "news_roundup": "AI + engineering news roundup",
    "fde_case": "FDE case study / client scenario",
    "martech": "Martech & AI-in-marketing",
    "leadership": "Engineering leadership / EM-for-AI-teams",
    "review_quiz": "Review & spaced-repetition quiz",
}

# Rotating subtopic banks per pillar (pillars without a bank, like
# news_roundup/review_quiz, are driven by search/history instead).
# "math_stats" has no weekday of its own — it's paired with Monday's ai_ml
# session (see build_plan) so both get dedicated coverage without adding an
# 8th weekday, per the "cover more than one topic in a day" allowance.
TOPIC_BANKS = {
    "math_stats": [
        # Linear algebra
        "vectors & vector spaces",
        "matrix operations (multiplication, transpose, inverse)",
        "dot product & cross product",
        "eigenvalues & eigenvectors",
        "singular value decomposition (SVD)",
        "norms (L1/L2) and intuition for high-dimensional space",
        # Calculus
        "derivatives & rate of change",
        "partial derivatives and gradients",
        "the chain rule (why backprop needs it)",
        "Jacobians & Hessians (light intuition)",
        "Taylor series (light intuition)",
        # Probability & statistics
        "probability distributions (Gaussian, Bernoulli, Poisson)",
        "conditional probability & Bayes' theorem",
        "expectation & variance",
        "covariance & correlation",
        "sampling & the central limit theorem",
        "hypothesis testing & p-values",
        "bias-variance tradeoff",
        "MLE vs. MAP estimation",
        # Optimization
        "loss/objective functions",
        "gradient descent and variants (SGD, momentum, Adam, RMSProp)",
        "convexity & local minima",
        "learning rate & schedules",
        "regularization (L1/L2, dropout)",
        "constrained optimization (light intuition)",
        # Information theory
        "entropy & cross-entropy",
        "KL divergence",
        "mutual information",
        "perplexity",
    ],
    "ai_ml": [
        # Classical ML
        "linear & logistic regression",
        "decision trees & random forests",
        "gradient boosting (XGBoost/LightGBM)",
        "support vector machines (SVMs)",
        "k-means & clustering",
        "dimensionality reduction (PCA, t-SNE, UMAP)",
        "ensemble methods",
        # Deep learning foundations
        "perceptrons & MLPs",
        "activation functions",
        "backpropagation",
        "CNNs",
        "RNNs & LSTMs (historical context, still shows up in interviews)",
        "regularization techniques for deep nets",
        "batch/layer normalization",
        "transfer learning",
        # LLMs & generative AI
        "transformer architecture",
        "self-attention & multi-head attention",
        "tokenization",
        "embeddings",
        "positional encoding",
        "pretraining vs. fine-tuning",
        "RLHF vs. DPO",
        "in-context learning",
        "prompt engineering",
        "context window management",
        "RAG architecture & retrieval strategies",
        "agentic systems & tool use",
        "multimodal models",
        "diffusion models",
        "reasoning models & test-time compute",
        # Evaluation & governance
        "eval design & benchmarks",
        "error analysis",
        "hallucination detection & mitigation",
        "guardrails & safety layers",
        "red-teaming",
        "bias & fairness metrics",
        "interpretability/explainability (SHAP, LIME)",
        # MLOps & production
        "model versioning",
        "feature stores",
        "data/model drift monitoring",
        "A/B testing for ML",
        "model serving & inference optimization",
        "quantization & distillation",
        "cost/latency tradeoffs",
        "CI/CD for ML pipelines",
    ],
    "swe": [
        # Distributed systems
        "CAP theorem",
        "consensus basics (Paxos/Raft)",
        "replication & partitioning",
        "load balancing",
        "eventual vs. strong consistency",
        # APIs & interfaces
        "REST vs. GraphQL vs. gRPC",
        "API versioning",
        "idempotency",
        "webhooks",
        # Data systems
        "relational vs. NoSQL databases",
        "indexing strategies",
        "transactions & ACID",
        "data warehouses vs. data lakes",
        "streaming systems (Kafka-style)",
        # Architecture patterns
        "microservices vs. monolith",
        "event-driven architecture",
        "caching layers",
        "message queues",
        # Reliability & operations
        "observability (logs/metrics/traces)",
        "SRE fundamentals",
        "incident response",
        "CI/CD pipelines",
        "infrastructure-as-code",
        # Security
        "authentication & authorization",
        "encryption basics",
        "least privilege",
        "secrets management",
        "common vulnerability classes (OWASP basics)",
        # Cloud & infrastructure
        "core AWS/GCP/Azure services",
        "containers & Kubernetes basics",
        "serverless tradeoffs",
    ],
    "fde_case": [
        "discovery & scoping ambiguous client requirements",
        "legacy system integration & data migration",
        "client stakeholder management & trust-building",
        "custom-for-this-client vs. reusable-platform tradeoffs",
        "on-site debugging & production incident handling under time pressure",
        "compliance & data privacy constraints in client environments",
        "translating a business KPI into a technical solution",
        "managing scope creep while shipping under deadline pressure",
        "post-deployment support, handoff, and knowledge transfer models",
    ],
    "martech": [
        "personalization & recommendation engines",
        "attribution modeling & measurement (including cookieless/privacy-first approaches)",
        "generative AI in content & creative production",
        "martech stack architecture (CDPs, CRMs, campaign orchestration)",
        "AI agents for marketing operations",
        "data clean rooms & first-party data strategy",
        "marketing analytics & forecasting with AI",
        "ethics & regulation — consent, disclosure, bias in targeting",
    ],
    "leadership": [
        "hiring & evaluating AI/ML engineers",
        "structuring teams around AI product work (research vs. applied split)",
        "managing technical debt in fast-moving AI codebases",
        "communicating AI risk & limitations to non-technical stakeholders",
        "roadmap planning under constant model/tooling churn",
        "build-vs-buy decisions for AI infrastructure",
        "org design for FDE-style client-facing engineering teams",
        "change management for AI-driven workflow shifts",
    ],
}

INTERVIEW_CATEGORIES = [
    "Coding/DS&A — arrays & strings, hashing, trees & graphs, recursion & dynamic programming, complexity analysis (senior-level: reasoning about it, not grinding it)",
    "System design (general) — scalability patterns; designing common systems like a URL shortener, rate limiter, chat system, notification system",
    "System design (ML/AI-specific) — RAG at scale, eval pipeline design, recommendation systems, agent platforms, feature store design",
    "Behavioral/leadership — conflict resolution, prioritization under ambiguity, influence without authority, giving hard feedback, scaling a team through change",
    "Case/product sense — client scoping walkthroughs, articulating tradeoffs out loud, build-vs-buy reasoning",
    "Martech/AI-product — personalization architecture, attribution modeling, GenAI content pipelines, measurement under privacy constraints",
]

PREFERRED_RESOURCES = """\
- 3Blue1Brown (Grant Sanderson) — always prefer for math intuition, linear algebra,
  neural network internals, attention/transformers, backprop, or probability.
- StatQuest (Josh Starmer) — classic ML/stats (regression, trees, gradient boosting,
  PCA, cross-validation), step by step.
- Andrej Karpathy — "Zero to Hero" series, mechanism-level depth on LLMs/neural nets.
- Two Minute Papers — quick summaries of new AI research papers.
- Yannic Kilcher — longer paper breakdowns.
- Computerphile — general CS concepts (algorithms, security, systems).
- ByteByteGo / Gaurav Sen — system design, diagrams-first.
- Fireship — very short, high-density explainers for tools/concepts.
- NeetCode — coding/DS&A interview questions with worked examples.
For martech/leadership topics with no obvious go-to channel, name a specific
well-known, credible resource (a talk, blog post, short course module) instead
of defaulting to generic marketing content."""


def load_state() -> dict:
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {"cursors": {}, "pending_interview": None, "history": []}


def save_state(state: dict) -> None:
    STATE_FILE.write_text(json.dumps(state, indent=2))


def _next_from_list(state: dict, cursor_key: str, items: list) -> str:
    """Rotating pick from `items`, persisting the cursor under `cursor_key`."""
    idx = state["cursors"].get(cursor_key, 0) % len(items)
    state["cursors"][cursor_key] = (idx + 1) % len(items)
    return items[idx]


def build_plan(state: dict, run_date: datetime, pillar_override: str = None) -> dict:
    """Decide today's pillar/topic/interview category and gather recall context.
    Mutates `state`'s cursors but does not save it."""
    weekday = run_date.weekday()
    pillar = pillar_override or PILLAR_BY_WEEKDAY[weekday]
    next_pillar = PILLAR_BY_WEEKDAY[(weekday + 1) % 7]

    plan = {
        "date": run_date.strftime("%Y-%m-%d"),
        "day_name": run_date.strftime("%A"),
        "pillar": pillar,
        "pillar_label": PILLAR_LABELS[pillar],
        "next_pillar_label": PILLAR_LABELS[next_pillar],
        "foundations_mode": run_date.date() < FOUNDATIONS_MODE_UNTIL,
        "topic": None,
        "math_topic": None,
        "fde_snippet_topic": None,
        "interview_category": _next_from_list(state, "interview_category", INTERVIEW_CATEGORIES),
        "pending_interview": state.get("pending_interview"),
        "recent_history": state.get("history", [])[-6:],
    }

    if pillar in TOPIC_BANKS:
        plan["topic"] = _next_from_list(state, pillar, TOPIC_BANKS[pillar])

    # Monday's AI/ML session also carries a paired math/stats foundation topic —
    # the two are taught together (math first, brief, then the AI/ML concept).
    if pillar == "ai_ml":
        plan["math_topic"] = _next_from_list(state, "math_stats", TOPIC_BANKS["math_stats"])

    # A short FDE case snippet runs every day except Thursday, where the
    # deep-dive slot itself already is the FDE case study.
    if pillar != "fde_case":
        plan["fde_snippet_topic"] = _next_from_list(state, "fde_snippet", TOPIC_BANKS["fde_case"])

    return plan


def _build_prompt(plan: dict) -> str:
    foundations = plan["foundations_mode"]

    if plan["pending_interview"]:
        answer_style = (
            "Write the model answer in plain, foundational language — define any technical "
            "term the first time you use it, don't assume unexplained jargon."
            if foundations else
            "Keep it concise and technical, staff-engineer level."
        )
        pending_block = f"""
0. YESTERDAY'S ANSWER (open with this, before anything else): Yesterday's interview
   question was, in category "{plan['pending_interview']['category']}":
   "{plan['pending_interview']['question']}"
   Assume I likely didn't get to attempt it. Give a concise (4-6 sentence) model answer
   to THIS EXACT question under a clear label (e.g. "↩️ Yesterday's Answer"), then move
   straight on to today's content. {answer_style}"""
    else:
        pending_block = ""

    if plan["recent_history"]:
        history_lines = "\n".join(
            f"- {h['date']} ({h['day_name']}, {h['pillar_label']}): {h['concept_summary']}"
            for h in plan["recent_history"]
        )
        history_context = f"Material covered earlier this week (for the recall check, and on Sundays the recap):\n{history_lines}"
        recall_instruction = """RECALL CHECK: Write 1-2 quick questions testing something from the material
   listed above (NOT today's new content) — spaced repetition, don't skip this even on
   light days. Just ask them; don't answer them."""
    else:
        history_context = "No prior material recorded yet (this is the first session)."
        recall_instruction = "RECALL CHECK: Skip it — say in one short line that recall material is still building up this week."

    plain_language_note = (
        " Write in plain, jargon-light language — define any technical term the first time "
        "you use it, as if for someone technical but new to this specific topic."
        if foundations else ""
    )

    if plan["pillar"] == "news_roundup":
        concept_block = f"""CONCEPT SLOT — DEEP NEWS ROUNDUP: Today's pillar is the news roundup. Search the web
   for 3-4 genuinely recent (last 3-5 days), dated AI/engineering developments relevant
   to a senior AI/engineering leader. For each: a 1-2 sentence summary plus why it
   matters for someone doing AI/eng leadership or FDE work.{plain_language_note} No
   learn-more link needed for this slot."""
    elif plan["pillar"] == "review_quiz":
        concept_block = f"""CONCEPT SLOT — WEEKLY RECAP & QUIZ: No new teaching today. Using the material listed
   above under "covered earlier this week", write one line per concept recapping what
   was covered Monday-Saturday, then turn 2-3 of them into quick recall questions
   (don't answer them).{plain_language_note} No learn-more link needed for this slot."""
    elif plan["pillar"] == "fde_case":
        concept_block = f"""CONCEPT SLOT — DEEP FDE CASE DIVE: Today's deep dive is the FDE case pillar. Write an
   applied scenario around "{plan['topic']}" — set the scene (2-3 sentences), the
   ambiguity or tension in it, then walk through a framework for reasoning through it
   and a concrete example resolution. This is the deep-dive version, so a full page is
   fine here.{plain_language_note} No learn-more link needed for this slot."""
    else:
        # Monday's AI/ML session pairs a math/stats foundation with the main
        # concept — cover both instead of just the one topic.
        if plan["pillar"] == "ai_ml" and plan.get("math_topic"):
            topic_line = (
                f'Today covers TWO linked topics: a math/stats foundation, "{plan["math_topic"]}", '
                f'and an AI/ML concept built on it, "{plan["topic"]}". Cover BOTH — a shorter section '
                f'on "{plan["math_topic"]}" first (just enough to build real intuition), then spend '
                f'most of the space on "{plan["topic"]}" as the main event. If there\'s a natural '
                "connection between the two, point it out explicitly; don't force one if there isn't."
            )
            video_ask = (
                'Then give a "watch/learn more" recommendation for EACH of the two topics '
                "(one resource for the math topic, one for the AI/ML topic)."
            )
        else:
            topic_line = f'The topic is "{plan["topic"]}".'
            video_ask = 'Then give ONE "watch/learn more" recommendation for the topic.'

        if foundations:
            concept_block = f"""CONCEPT OF THE DAY: {topic_line} Assume I'm technical and experienced
   generally, but NEW to this specific material — I'm deliberately spending the next few
   months building 101-level foundations before going deep, so don't skip basics here even
   though you would for other senior-level topics. For each topic covered today, structure
   it in two parts:
   THE BASICS: If it's really a comparison of multiple building-block ideas (e.g. "REST vs
   GraphQL vs gRPC" or "fine-tuning vs prompting vs RAG"), first explain EACH one on its
   own in plain language with a simple analogy — what it is and what problem it solves —
   before any comparison. If it's a single concept, just explain what it is, why it exists,
   and the simplest possible mental model for it.
   HOW IT'S USED / WHY IT MATTERS: Only after the basics, get into the tradeoffs, when to
   use which, a real-world failure mode, and one line on how this shows up in an
   FDE/leadership context. Keep this part shorter than the basics.
   Define any technical term the first time you use it — don't assume unexplained jargon.
   {video_ask} Prioritize a genuinely 101/beginner-level intro resource (one per
   building-block concept if there are several, e.g. a "what is REST" video and a "what is
   GraphQL" video) over deep technical talks. Pick from this preferred list where it fits
   (don't force 3Blue1Brown into everything):
{PREFERRED_RESOURCES}
   Only give a URL you found via web search and are sure is correct/live. If you're not
   sure of the exact URL, name the channel/video and give a precise search phrase
   instead (e.g. "search YouTube: what is REST API for beginners") rather than guessing a
   link."""
        else:
            concept_block = f"""CONCEPT OF THE DAY: {topic_line} Explain it the way you'd explain it to a
   strong staff engineer — skip 101-level basics, go straight to the mechanism, why it
   matters, and a real tradeoff or production failure mode. Close with one line on how this
   shows up in an FDE/leadership context. {video_ask} Pick whichever fits best from this
   preferred list (don't force 3Blue1Brown into everything):
{PREFERRED_RESOURCES}
   Only give a URL you found via web search and are sure is correct/live. If you're not
   sure of the exact URL, name the channel/video and give a precise search phrase
   instead (e.g. "search YouTube: 3Blue1Brown attention in transformers") rather than
   guessing a link."""

    if plan["fde_snippet_topic"]:
        fde_snippet_block = f"""FDE CASE SNIPPET: Write a short applied scenario (2-4 sentences) around
   "{plan['fde_snippet_topic']}" that I have to reason through — end on an open question,
   don't give the answer, keep it brief.{plain_language_note}"""
    else:
        fde_snippet_block = ""

    interview_block = f"""INTERVIEW QUESTION OF THE DAY — category: {plan['interview_category']}
   Write ONE realistic interview question in this category, pitched at a senior
   candidate. Give ONLY the question — no answer, no hints. I'll attempt it myself; the
   model answer gets revealed at the start of tomorrow's message."""

    sign_off_line = (
        f"one line signing off, noting tomorrow's deep-dive pillar is \"{plan['next_pillar_label']}\" "
        "(use that exact phrase — don't rename or paraphrase it; don't invent interactive commands "
        "like \"reply X\" — this is a one-way message, not a live chat)"
    )

    if foundations:
        calibration = """I'm senior in my actual job (management/stakeholder work), but genuinely NEW to a lot
of the hands-on AI/engineering material this session covers — I'm deliberately spending
the next few months building 101-level foundations before ramping back up to advanced
material. So across EVERY section below (not just the concept of the day): explain things
plainly, define technical terms and acronyms the first time you use them, don't assume
unexplained jargon, and don't rush past the basics to get to the "interesting" tradeoff
part. It's fine for an explanation to spend most of its length on fundamentals."""
    else:
        calibration = """I'm senior, not a beginner. Skip 101-level definitions unless I ask for them. Go
straight to the mechanism, the tradeoff, or the "here's what actually breaks in
production" angle."""

    return f"""You are my daily learning coach. I'm a senior manager leading AI/engineering
teams and working toward an FDE (Forward Deployed Engineer) Lead role. {calibration} This
is maintenance, not cramming: keep the tone like a smart peer doing a daily sync. Optimize
for retention over coverage.

Today is {plan['day_name']}, {plan['date']}. Today's deep-dive pillar is: {plan['pillar_label']}.

{history_context}

Write today's message with these parts, IN THIS ORDER:
{pending_block}
1. QUICK-HIT NEWS: Search the web for 2-3 recent, dated AI/engineering developments
   worth knowing about (skip this if today's pillar is the news roundup — that gets its
   own deeper treatment below instead). Keep each to one line with a date.

2. {concept_block}

3. {fde_snippet_block if fde_snippet_block else "(no separate FDE case snippet today — the deep dive above covers it)"}

4. {interview_block}

5. {recall_instruction}

6. SIGN-OFF: {sign_off_line}.

FORMATTING: This is a plain-text email/Telegram message, not a markdown renderer — any
markdown you write will show up as literal stray characters, not formatting. So: never
use asterisks for bold/italic (*, **), never use # headers, never use backtick code
spans, never use markdown links ([text](url)) — just write the URL bare. Use plain
sentence structure, blank lines between ideas (never more than one blank line in a row),
and a simple "-" for list items where needed. Emoji are fine sparingly for section
headers. Do not add any preamble like "Here's your session" — start directly with the
content. Do not narrate your search process or explain your choices anywhere in the
output.

After ALL of the above, on new lines, append EXACTLY this machine-readable block (it will
be stripped before sending to me, so it must not duplicate content I need to read — just
the two lines below, nothing else in the block):
<<<STATE>>>
INTERVIEW_QUESTION: <verbatim text of the interview question you wrote in part 4, one line>
CONCEPT_SUMMARY: <one line, under 15 words, summarizing today's main content (the concept/news-roundup/case/recap topic)>
<<<END_STATE>>>"""


def _split_state_block(text: str) -> tuple:
    marker = "<<<STATE>>>"
    end_marker = "<<<END_STATE>>>"
    if marker not in text:
        return text.strip(), {}
    body, _, rest = text.partition(marker)
    state_block, _, _ = rest.partition(end_marker)
    meta = {}
    for line in state_block.strip().splitlines():
        if ":" in line:
            key, _, value = line.partition(":")
            meta[key.strip()] = value.strip()
    return body.strip(), meta


def generate_nugget(plan: dict) -> tuple:
    """Call Claude (with web search) to produce today's coaching message.
    Returns (message_text, meta_dict)."""
    client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from env

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=6000,
        tools=[{"type": "web_search_20250305", "name": "web_search"}],
        messages=[{"role": "user", "content": _build_prompt(plan)}],
    )

    text_parts = [block.text for block in response.content if block.type == "text"]
    raw = "\n".join(text_parts).strip()

    header = f"📅 {plan['day_name']}, {plan['date']} — Today's deep dive: {plan['pillar_label']}"
    body, meta = _split_state_block(raw)
    # Web-search citation markers leave stray blank lines behind when stripped;
    # collapse any run of 2+ blank lines down to exactly one.
    body = re.sub(r"\n\s*\n(\s*\n)+", "\n\n", body)
    return f"{header}\n\n{body}", meta


def send_email(subject: str, message: str) -> None:
    import urllib.request
    import urllib.error

    api_key = os.environ["RESEND_API_KEY"]
    from_address = os.environ.get("EMAIL_FROM", "onboarding@resend.dev")
    to_address = os.environ["EMAIL_TO"]

    payload = json.dumps({
        "from": from_address,
        "to": [to_address],
        "subject": subject,
        "text": message,
    }).encode("utf-8")

    request = urllib.request.Request(
        "https://api.resend.com/emails",
        data=payload,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "User-Agent": "Mozilla/5.0 (compatible; daily-ai-nugget/1.0)",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request) as response:
            result = json.loads(response.read())
    except urllib.error.HTTPError as e:
        raise RuntimeError(f"Resend API error {e.code}: {e.read().decode()}") from e

    print(f"Sent email to {to_address}. Resend id: {result.get('id')}")


TELEGRAM_MAX_LEN = 4000  # Telegram's hard limit is 4096 chars; leave some headroom


def _chunk_message(message: str, max_len: int) -> list:
    """Split into chunks <= max_len, breaking on blank lines/newlines where possible."""
    if len(message) <= max_len:
        return [message]

    chunks = []
    remaining = message
    while len(remaining) > max_len:
        split_at = remaining.rfind("\n\n", 0, max_len)
        if split_at == -1:
            split_at = remaining.rfind("\n", 0, max_len)
        if split_at == -1:
            split_at = max_len
        chunks.append(remaining[:split_at].strip())
        remaining = remaining[split_at:].strip()
    if remaining:
        chunks.append(remaining)
    return chunks


def send_telegram(message: str) -> None:
    import urllib.request
    import urllib.error

    bot_token = os.environ["TELEGRAM_BOT_TOKEN"]
    chat_id = os.environ["TELEGRAM_CHAT_ID"]

    for chunk in _chunk_message(message, TELEGRAM_MAX_LEN):
        payload = json.dumps({
            "chat_id": chat_id,
            "text": chunk,
        }).encode("utf-8")

        request = urllib.request.Request(
            f"https://api.telegram.org/bot{bot_token}/sendMessage",
            data=payload,
            headers={
                "Content-Type": "application/json",
                "User-Agent": "Mozilla/5.0 (compatible; daily-ai-nugget/1.0)",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request) as response:
                result = json.loads(response.read())
        except urllib.error.HTTPError as e:
            raise RuntimeError(f"Telegram API error {e.code}: {e.read().decode()}") from e

        print(f"Sent Telegram message. Message id: {result['result']['message_id']}")


def main():
    parser = argparse.ArgumentParser(description="Daily FDE learning coach sender")
    parser.add_argument("--dry-run", action="store_true", help="Print message, don't send")
    parser.add_argument("--pillar", type=str, choices=list(PILLAR_LABELS),
                         help="Override today's deep-dive pillar (for testing)")
    parser.add_argument("--reset-state", action="store_true",
                         help="Wipe coach_state.json (rotation cursors, pending question, history)")
    args = parser.parse_args()

    if args.reset_state:
        save_state({"cursors": {}, "pending_interview": None, "history": []})
        print("Coach state reset.")

    state = load_state()
    run_date = now_ist()
    plan = build_plan(state, run_date, pillar_override=args.pillar)
    print(f"[{run_date.isoformat(timespec='seconds')}] {plan['day_name']} — pillar: {plan['pillar_label']}"
          + (f" — topic: {plan['topic']}" if plan["topic"] else ""))

    message, meta = generate_nugget(plan)
    print("---- MESSAGE ----")
    print(message)
    print("-----------------")

    if meta.get("INTERVIEW_QUESTION"):
        state["pending_interview"] = {
            "category": plan["interview_category"],
            "question": meta["INTERVIEW_QUESTION"],
        }
    state.setdefault("history", []).append({
        "date": plan["date"],
        "day_name": plan["day_name"],
        "pillar_label": plan["pillar_label"],
        "concept_summary": meta.get("CONCEPT_SUMMARY", plan["topic"] or plan["pillar_label"]),
    })
    state["history"] = state["history"][-8:]
    save_state(state)

    if args.dry_run:
        print("(dry run — not sent, but state was still advanced)")
        return

    subject = f"Daily Coach — {plan['day_name']}: {plan['topic'] or plan['pillar_label']}"
    send_email(subject, message)
    send_telegram(message)


if __name__ == "__main__":
    sys.exit(main())
