#!/usr/bin/env python3
"""
Daily FDE Learning Coach Bot
----------------------------
A 15-20 minute daily learning session for a senior manager/FDE-lead
maintaining hands-on AI/ML + engineering depth. Each day has a deep-dive
pillar based on day of week (Mon=AI/ML, Tue=SWE, Wed=news roundup,
Thu=FDE case study, Fri=Martech, Sat=eng leadership, Sun=weekly recap/quiz),
wrapped in the same lightweight daily template every day. Generated by
Claude with web search, then sent by email (Resend API) and Telegram
(Telegram Bot API).

Designed to run on a schedule (cron / GitHub Actions) alongside your
existing WhatsApp goal-notifier script.

SETUP
-----
1. pip install anthropic python-dotenv
2. Email (Resend): create a free account at https://resend.com and copy
   an API key from the dashboard (starts with "re_").
3. Telegram: message @BotFather on Telegram, send "/newbot", follow the
   prompts, and copy the bot token it gives you. Then send your new bot
   any message (e.g. "hi") so it can see your chat, and visit
   https://api.telegram.org/bot<YOUR_TOKEN>/getUpdates in a browser to
   find your numeric chat id under "message" -> "chat" -> "id".
4. Create a .env file (same folder) with:
       ANTHROPIC_API_KEY=sk-ant-...
       RESEND_API_KEY=re_...
       EMAIL_TO=you@example.com
       EMAIL_FROM=onboarding@resend.dev              # optional; see note below
       TELEGRAM_BOT_TOKEN=123456789:AA...
       TELEGRAM_CHAT_ID=123456789
   Note: the shared "onboarding@resend.dev" sender only delivers to the
   email address you signed up to Resend with. To send to any address,
   verify your own domain in the Resend dashboard and set EMAIL_FROM to
   an address on it (e.g. bot@yourdomain.com).
5. Test: python daily_ai_nugget.py --dry-run   (prints message, doesn't send)
6. Schedule it (see .github/workflows/daily-nugget.yml for the GitHub
   Actions version, which runs daily at 9:30 AM IST).

CUSTOMIZING TOPICS
------------------
Edit TOPIC_BANKS to change what each pillar covers. Each pillar has its
own rotating cursor persisted in coach_state.json, so subtopics cycle
through without repeating. PILLAR_BY_WEEKDAY controls which pillar is the
deep-dive for which day (index 0 = Monday ... 6 = Sunday, matching
datetime.weekday()).

NOTE ON INTERACTIVITY
----------------------
The source instructions this bot follows (a conversational "coach" prompt)
assume a live chat where you can reply "quiz me", "more depth", etc., and
where the coach waits to see if you attempted yesterday's interview
question before revealing the answer. This bot is a one-way scheduled
send with no reply-parsing, so those interactive bits are adapted:
the model answer to each day's interview question is always revealed at
the start of the *next* day's message (regardless of whether you actually
attempted it), and steering commands aren't wired up.
"""

import os
import re
import sys
import json
import argparse
from datetime import datetime, timezone, timedelta
from pathlib import Path

from dotenv import load_dotenv
import anthropic

if sys.stdout.encoding != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")

load_dotenv()

SCRIPT_DIR = Path(__file__).parent
STATE_FILE = SCRIPT_DIR / "coach_state.json"

IST = timezone(timedelta(hours=5, minutes=30))


def now_ist() -> datetime:
    return datetime.now(IST)


# Day-of-week (datetime.weekday(): Monday=0 ... Sunday=6) -> deep-dive pillar.
PILLAR_BY_WEEKDAY = [
    "ai_ml",         # Monday
    "swe",           # Tuesday
    "news_roundup",  # Wednesday
    "fde_case",      # Thursday
    "martech",       # Friday
    "leadership",    # Saturday
    "review_quiz",   # Sunday
]

PILLAR_LABELS = {
    "ai_ml": "AI/ML core concepts",
    "swe": "Software & systems engineering",
    "news_roundup": "AI + engineering news roundup",
    "fde_case": "FDE case study / client scenario",
    "martech": "Martech & AI-in-marketing",
    "leadership": "Engineering leadership / EM-for-AI-teams",
    "review_quiz": "Review & spaced-repetition quiz",
}

# Rotating subtopic banks per pillar (pillars without a bank, like
# news_roundup/review_quiz, are driven by search/history instead).
TOPIC_BANKS = {
    "ai_ml": [
        "LLM architecture & attention mechanics",
        "embeddings & vector search",
        "RAG design patterns and failure modes",
        "fine-tuning vs. prompting vs. RAG: when each wins",
        "evals & benchmarking for LLM systems",
        "agents & tool use",
        "context window management",
        "hallucination mitigation",
        "guardrails & safety layers",
        "model routing/orchestration",
        "quantization & inference cost tradeoffs",
        "classic ML (trees, regression, clustering) refreshers",
        "MLOps & model lifecycle",
        "prompt engineering patterns",
        "multimodal models",
        "reasoning models & test-time compute",
    ],
    "swe": [
        "distributed systems fundamentals (CAP, consensus, replication)",
        "API design (REST/GraphQL/gRPC tradeoffs)",
        "database internals & indexing",
        "caching strategies",
        "event-driven architecture",
        "microservices vs. monolith tradeoffs",
        "observability (logging/tracing/metrics)",
        "CI/CD & deployment strategies",
        "security fundamentals (authN/authZ, secrets, least privilege)",
        "cloud architecture (AWS/GCP/Azure core services)",
        "performance & scalability",
        "data pipeline design",
        "infrastructure-as-code",
        "containers & orchestration (Docker/Kubernetes basics an FDE needs)",
    ],
    "fde_case": [
        "scoping an ambiguous client ask into a shippable v1",
        "integrating with a client's messy legacy systems/data",
        "building trust with a skeptical technical stakeholder",
        'balancing "custom for this client" vs. "reusable platform"',
        "handling data privacy/compliance constraints in a client environment",
        "debugging a production issue on-site under time pressure",
        "translating a business KPI into a technical solution",
        "managing scope creep mid-deployment",
    ],
    "martech": [
        "AI-driven personalization engines",
        "marketing attribution & measurement in a cookieless/privacy-first world",
        "generative AI in content/creative production",
        "martech stack architecture (CDPs, CRMs, campaign orchestration)",
        "AI agents for marketing ops",
        "data clean rooms",
        "AI in marketing analytics/forecasting",
        "ethical/regulatory issues in AI marketing (consent, disclosure, bias)",
    ],
    "leadership": [
        "hiring and evaluating AI/ML engineers",
        "structuring teams around AI product work",
        "balancing research vs. shipping",
        "managing technical debt in fast-moving AI codebases",
        "communicating AI limitations/risk to non-technical stakeholders",
        "roadmap planning under model/tooling churn",
        "build-vs-buy decisions for AI infra",
        "org design for FDE-style client-facing engineering teams",
    ],
}

INTERVIEW_CATEGORIES = [
    "Coding/DS&A (rusty-but-senior level: reasoning about complexity and clean logic, not LeetCode grinding)",
    "System design — general (e.g. a URL shortener, a rate limiter, a notification system)",
    "System design — ML/AI specific (e.g. a RAG system at scale, an eval pipeline, a recommendation system, an agent platform)",
    "Behavioral/leadership (conflict resolution, prioritization under ambiguity, influencing without authority, managing a team through a pivot, giving hard feedback)",
    "FDE/case/product-sense (client scoping, tradeoff articulation, walking through how you'd approach a deployment)",
    "Martech/AI-product (personalization architecture, attribution modeling, GenAI content pipelines, measurement under privacy constraints)",
]

PREFERRED_RESOURCES = """\
- 3Blue1Brown (Grant Sanderson) — always prefer for math intuition, linear algebra,
  neural network internals, attention/transformers, backprop, or probability.
- StatQuest (Josh Starmer) — classic ML/stats (regression, trees, gradient boosting,
  PCA, cross-validation), step by step.
- Andrej Karpathy — "Zero to Hero" series, mechanism-level depth on LLMs/neural nets.
- Two Minute Papers — quick summaries of new AI research papers.
- Yannic Kilcher — longer paper breakdowns.
- Computerphile — general CS concepts (algorithms, security, systems).
- ByteByteGo / Gaurav Sen — system design, diagrams-first.
- Fireship — very short, high-density explainers for tools/concepts.
- NeetCode — coding/DS&A interview questions with worked examples.
For martech/leadership topics with no obvious go-to channel, name a specific
well-known, credible resource (a talk, blog post, short course module) instead
of defaulting to generic marketing content."""


def load_state() -> dict:
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {"cursors": {}, "pending_interview": None, "history": []}


def save_state(state: dict) -> None:
    STATE_FILE.write_text(json.dumps(state, indent=2))


def _next_from_list(state: dict, cursor_key: str, items: list) -> str:
    """Rotating pick from `items`, persisting the cursor under `cursor_key`."""
    idx = state["cursors"].get(cursor_key, 0) % len(items)
    state["cursors"][cursor_key] = (idx + 1) % len(items)
    return items[idx]


def build_plan(state: dict, run_date: datetime, pillar_override: str = None) -> dict:
    """Decide today's pillar/topic/interview category and gather recall context.
    Mutates `state`'s cursors but does not save it."""
    weekday = run_date.weekday()
    pillar = pillar_override or PILLAR_BY_WEEKDAY[weekday]
    next_pillar = PILLAR_BY_WEEKDAY[(weekday + 1) % 7]

    plan = {
        "date": run_date.strftime("%Y-%m-%d"),
        "day_name": run_date.strftime("%A"),
        "pillar": pillar,
        "pillar_label": PILLAR_LABELS[pillar],
        "next_pillar_label": PILLAR_LABELS[next_pillar],
        "topic": None,
        "fde_snippet_topic": None,
        "interview_category": _next_from_list(state, "interview_category", INTERVIEW_CATEGORIES),
        "pending_interview": state.get("pending_interview"),
        "recent_history": state.get("history", [])[-6:],
    }

    if pillar in TOPIC_BANKS:
        plan["topic"] = _next_from_list(state, pillar, TOPIC_BANKS[pillar])

    # A short FDE case snippet runs every day except Thursday, where the
    # deep-dive slot itself already is the FDE case study.
    if pillar != "fde_case":
        plan["fde_snippet_topic"] = _next_from_list(state, "fde_snippet", TOPIC_BANKS["fde_case"])

    return plan


def _build_prompt(plan: dict) -> str:
    if plan["pending_interview"]:
        pending_block = f"""
0. YESTERDAY'S ANSWER (open with this, before anything else): Yesterday's interview
   question was, in category "{plan['pending_interview']['category']}":
   "{plan['pending_interview']['question']}"
   Assume I likely didn't get to attempt it. Give a concise (4-6 sentence) model answer
   to THIS EXACT question under a clear label (e.g. "↩️ Yesterday's Answer"), then move
   straight on to today's content."""
    else:
        pending_block = ""

    if plan["recent_history"]:
        history_lines = "\n".join(
            f"- {h['date']} ({h['day_name']}, {h['pillar_label']}): {h['concept_summary']}"
            for h in plan["recent_history"]
        )
        history_context = f"Material covered earlier this week (for the recall check, and on Sundays the recap):\n{history_lines}"
        recall_instruction = """RECALL CHECK: Write 1-2 quick questions testing something from the material
   listed above (NOT today's new content) — spaced repetition, don't skip this even on
   light days. Just ask them; don't answer them."""
    else:
        history_context = "No prior material recorded yet (this is the first session)."
        recall_instruction = "RECALL CHECK: Skip it — say in one short line that recall material is still building up this week."

    if plan["pillar"] == "news_roundup":
        concept_block = """CONCEPT SLOT — DEEP NEWS ROUNDUP: Today's pillar is the news roundup. Search the web
   for 3-4 genuinely recent (last 3-5 days), dated AI/engineering developments relevant
   to a senior AI/engineering leader. For each: a 1-2 sentence summary plus why it
   matters for someone doing AI/eng leadership or FDE work. No learn-more link needed
   for this slot."""
    elif plan["pillar"] == "review_quiz":
        concept_block = """CONCEPT SLOT — WEEKLY RECAP & QUIZ: No new teaching today. Using the material listed
   above under "covered earlier this week", write one line per concept recapping what
   was covered Monday-Saturday, then turn 2-3 of them into quick recall questions
   (don't answer them). No learn-more link needed for this slot."""
    elif plan["pillar"] == "fde_case":
        concept_block = f"""CONCEPT SLOT — DEEP FDE CASE DIVE: Today's deep dive is the FDE case pillar. Write an
   applied scenario around "{plan['topic']}" — set the scene (2-3 sentences), the
   ambiguity or tension in it, then walk through a framework for reasoning through it
   and a concrete example resolution. This is the deep-dive version, so a full page is
   fine here. No learn-more link needed for this slot."""
    else:
        concept_block = f"""CONCEPT OF THE DAY: Explain "{plan['topic']}" the way you'd explain it to a strong
   staff engineer — skip 101-level basics, go straight to the mechanism, why it matters,
   and a real tradeoff or production failure mode. Close with one line on how this shows
   up in an FDE/leadership context. Then give ONE "watch/learn more" recommendation —
   whichever fits the topic best from this preferred list (don't force 3Blue1Brown into
   everything):
{PREFERRED_RESOURCES}
   Only give a URL you found via web search and are sure is correct/live. If you're not
   sure of the exact URL, name the channel/video and give a precise search phrase
   instead (e.g. "search YouTube: 3Blue1Brown attention in transformers") rather than
   guessing a link."""

    if plan["fde_snippet_topic"]:
        fde_snippet_block = f"""FDE CASE SNIPPET: Write a short applied scenario (2-4 sentences) around
   "{plan['fde_snippet_topic']}" that I have to reason through — end on an open question,
   don't give the answer, keep it brief."""
    else:
        fde_snippet_block = ""

    interview_block = f"""INTERVIEW QUESTION OF THE DAY — category: {plan['interview_category']}
   Write ONE realistic interview question in this category, pitched at a senior
   candidate. Give ONLY the question — no answer, no hints. I'll attempt it myself; the
   model answer gets revealed at the start of tomorrow's message."""

    sign_off_line = (
        f"one line signing off, noting tomorrow's deep-dive pillar is \"{plan['next_pillar_label']}\" "
        "(use that exact phrase — don't rename or paraphrase it; don't invent interactive commands "
        "like \"reply X\" — this is a one-way message, not a live chat)"
    )

    return f"""You are my daily learning coach. I'm a senior manager leading AI/engineering
teams and working toward an FDE (Forward Deployed Engineer) Lead role. I'm senior, not a
beginner — skip 101-level definitions, go straight to mechanism/tradeoffs/what-breaks-in-
production. This is maintenance, not cramming: keep the tone like a smart peer doing a
daily sync. Optimize for retention over coverage.

Today is {plan['day_name']}, {plan['date']}. Today's deep-dive pillar is: {plan['pillar_label']}.

{history_context}

Write today's message with these parts, IN THIS ORDER:
{pending_block}
1. QUICK-HIT NEWS: Search the web for 2-3 recent, dated AI/engineering developments
   worth knowing about (skip this if today's pillar is the news roundup — that gets its
   own deeper treatment below instead). Keep each to one line with a date.

2. {concept_block}

3. {fde_snippet_block if fde_snippet_block else "(no separate FDE case snippet today — the deep dive above covers it)"}

4. {interview_block}

5. {recall_instruction}

6. SIGN-OFF: {sign_off_line}.

FORMATTING: This is a plain-text email/Telegram message, not a markdown renderer — any
markdown you write will show up as literal stray characters, not formatting. So: never
use asterisks for bold/italic (*, **), never use # headers, never use backtick code
spans, never use markdown links ([text](url)) — just write the URL bare. Use plain
sentence structure, blank lines between ideas (never more than one blank line in a row),
and a simple "-" for list items where needed. Emoji are fine sparingly for section
headers. Do not add any preamble like "Here's your session" — start directly with the
content. Do not narrate your search process or explain your choices anywhere in the
output.

After ALL of the above, on new lines, append EXACTLY this machine-readable block (it will
be stripped before sending to me, so it must not duplicate content I need to read — just
the two lines below, nothing else in the block):
<<<STATE>>>
INTERVIEW_QUESTION: <verbatim text of the interview question you wrote in part 4, one line>
CONCEPT_SUMMARY: <one line, under 15 words, summarizing today's main content (the concept/news-roundup/case/recap topic)>
<<<END_STATE>>>"""


def _split_state_block(text: str) -> tuple:
    marker = "<<<STATE>>>"
    end_marker = "<<<END_STATE>>>"
    if marker not in text:
        return text.strip(), {}
    body, _, rest = text.partition(marker)
    state_block, _, _ = rest.partition(end_marker)
    meta = {}
    for line in state_block.strip().splitlines():
        if ":" in line:
            key, _, value = line.partition(":")
            meta[key.strip()] = value.strip()
    return body.strip(), meta


def generate_nugget(plan: dict) -> tuple:
    """Call Claude (with web search) to produce today's coaching message.
    Returns (message_text, meta_dict)."""
    client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY from env

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=6000,
        tools=[{"type": "web_search_20250305", "name": "web_search"}],
        messages=[{"role": "user", "content": _build_prompt(plan)}],
    )

    text_parts = [block.text for block in response.content if block.type == "text"]
    raw = "\n".join(text_parts).strip()

    header = f"📅 {plan['day_name']}, {plan['date']} — Today's deep dive: {plan['pillar_label']}"
    body, meta = _split_state_block(raw)
    # Web-search citation markers leave stray blank lines behind when stripped;
    # collapse any run of 2+ blank lines down to exactly one.
    body = re.sub(r"\n\s*\n(\s*\n)+", "\n\n", body)
    return f"{header}\n\n{body}", meta


def send_email(subject: str, message: str) -> None:
    import urllib.request
    import urllib.error

    api_key = os.environ["RESEND_API_KEY"]
    from_address = os.environ.get("EMAIL_FROM", "onboarding@resend.dev")
    to_address = os.environ["EMAIL_TO"]

    payload = json.dumps({
        "from": from_address,
        "to": [to_address],
        "subject": subject,
        "text": message,
    }).encode("utf-8")

    request = urllib.request.Request(
        "https://api.resend.com/emails",
        data=payload,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "User-Agent": "Mozilla/5.0 (compatible; daily-ai-nugget/1.0)",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request) as response:
            result = json.loads(response.read())
    except urllib.error.HTTPError as e:
        raise RuntimeError(f"Resend API error {e.code}: {e.read().decode()}") from e

    print(f"Sent email to {to_address}. Resend id: {result.get('id')}")


TELEGRAM_MAX_LEN = 4000  # Telegram's hard limit is 4096 chars; leave some headroom


def _chunk_message(message: str, max_len: int) -> list:
    """Split into chunks <= max_len, breaking on blank lines/newlines where possible."""
    if len(message) <= max_len:
        return [message]

    chunks = []
    remaining = message
    while len(remaining) > max_len:
        split_at = remaining.rfind("\n\n", 0, max_len)
        if split_at == -1:
            split_at = remaining.rfind("\n", 0, max_len)
        if split_at == -1:
            split_at = max_len
        chunks.append(remaining[:split_at].strip())
        remaining = remaining[split_at:].strip()
    if remaining:
        chunks.append(remaining)
    return chunks


def send_telegram(message: str) -> None:
    import urllib.request
    import urllib.error

    bot_token = os.environ["TELEGRAM_BOT_TOKEN"]
    chat_id = os.environ["TELEGRAM_CHAT_ID"]

    for chunk in _chunk_message(message, TELEGRAM_MAX_LEN):
        payload = json.dumps({
            "chat_id": chat_id,
            "text": chunk,
        }).encode("utf-8")

        request = urllib.request.Request(
            f"https://api.telegram.org/bot{bot_token}/sendMessage",
            data=payload,
            headers={
                "Content-Type": "application/json",
                "User-Agent": "Mozilla/5.0 (compatible; daily-ai-nugget/1.0)",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request) as response:
                result = json.loads(response.read())
        except urllib.error.HTTPError as e:
            raise RuntimeError(f"Telegram API error {e.code}: {e.read().decode()}") from e

        print(f"Sent Telegram message. Message id: {result['result']['message_id']}")


def main():
    parser = argparse.ArgumentParser(description="Daily FDE learning coach sender")
    parser.add_argument("--dry-run", action="store_true", help="Print message, don't send")
    parser.add_argument("--pillar", type=str, choices=list(PILLAR_LABELS),
                         help="Override today's deep-dive pillar (for testing)")
    parser.add_argument("--reset-state", action="store_true",
                         help="Wipe coach_state.json (rotation cursors, pending question, history)")
    args = parser.parse_args()

    if args.reset_state:
        save_state({"cursors": {}, "pending_interview": None, "history": []})
        print("Coach state reset.")

    state = load_state()
    run_date = now_ist()
    plan = build_plan(state, run_date, pillar_override=args.pillar)
    print(f"[{run_date.isoformat(timespec='seconds')}] {plan['day_name']} — pillar: {plan['pillar_label']}"
          + (f" — topic: {plan['topic']}" if plan["topic"] else ""))

    message, meta = generate_nugget(plan)
    print("---- MESSAGE ----")
    print(message)
    print("-----------------")

    if meta.get("INTERVIEW_QUESTION"):
        state["pending_interview"] = {
            "category": plan["interview_category"],
            "question": meta["INTERVIEW_QUESTION"],
        }
    state.setdefault("history", []).append({
        "date": plan["date"],
        "day_name": plan["day_name"],
        "pillar_label": plan["pillar_label"],
        "concept_summary": meta.get("CONCEPT_SUMMARY", plan["topic"] or plan["pillar_label"]),
    })
    state["history"] = state["history"][-8:]
    save_state(state)

    if args.dry_run:
        print("(dry run — not sent, but state was still advanced)")
        return

    subject = f"Daily Coach — {plan['day_name']}: {plan['topic'] or plan['pillar_label']}"
    send_email(subject, message)
    send_telegram(message)


if __name__ == "__main__":
    sys.exit(main())
